### ISSUE TITLE
Should we allow PrivateIdentifier after . in SimpleMemberExpression?

### ISSUE THREAD

**Issue by JLHwung** [tc39/proposal-bind-this#20]
The current syntax
```
SimpleMemberExpression[Yield, Await] :
  IdentifierReference[?Yield, ?Await]
  SimpleMemberExpression[?Yield, ?Await] . IdentifierName
  ( Expression[+In, ?Yield, ?Await] )
```
disallows `o.#p` as a simple member expression, instead one would have to parenthesize it into `(o.#p)`.

Is it intentional? From users's perspective, I would expect it suffices to replace `.foo` with `.#foo` when transitioning from a public property to a private one.

**Comment by js-choi** [comment]
I agree; I think that we should allow `rec::obj.#fn`. I will amend the proposal when I have time.

This is a cross-cutting concern with decorators’ syntax, with which bind-this shares.
`@obj.#fn class {}` should also be valid; it may be worth opening an issue there about this too.
