### ISSUE TITLE
Typo in "README.md"

### ISSUE THREAD

**Issue by Andrew-Cottrell** [tc39/proposal-bind-this#23]
https://github.com/tc39/proposal-bind-this/blob/d4c578ace8f90888a02f7425b83c6661e3c94bc0/README.md?plain=1#L155

> `.bind` and `.call` are arguably three of the most commonly used functions in all JavaScript.

I assume that should be **two** rather than **three**. Before https://github.com/tc39/proposal-bind-this/commit/53141194dfb3fe7f06761b39bf64999b41e28d80, that sentence was 

> `.bind`, `.call`, and `.apply` are arguably three of the most commonly used functions in all JavaScript.

**Comment by theScottyJam** [comment]
I threw together a PR to fix this: https://github.com/tc39/proposal-bind-this/pull/24

(I haven't done this before, so if I did something wrong, feel free to let me know)
